{
 "title": "Big Peach",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,2s,5s,10s,15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$interval),\n  avg(solar_power) AS \"Solar\",\n  avg(load_power) AS \"Load\",\n  avg(solar_power - load_power) AS \"Net\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$interval),\n  avg(battery_voltage) AS \"Voltage\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  LEAST(((battery_voltage - 11.5) * (100 - 0) / (12.75 - 11.5) + 0), 100)\nFROM readings\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Readings Table",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  (select count(1) from readings) as \"Records\",\n  (select pg_total_relation_size('readings') / 1024.0 / 1024.0) as \"Size\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$interval),\n  avg(device_temperature) AS \"Controller\",\n  avg(battery_temperature) AS \"Battery\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Read Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$interval),\n  avg(EXTRACT(milliseconds from read_duration)) AS \"Duration\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Generated Energy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  generated_energy_today AS \"Today\",\n  generated_energy_month AS \"Month\",\n  generated_energy_year AS \"Year\",\n  generated_energy_total AS \"Total\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Consumed Energy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  consumed_energy_today AS \"Today\",\n  consumed_energy_month AS \"Month\",\n  consumed_energy_year AS \"Year\",\n  consumed_energy_total AS \"Total\"\nFROM readings\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Energy Generated",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "select\n    time,\n    generated_energy / 3600000 as \"Generated\"\nfrom\n\t  daily_energy\nwhere time > now() - interval '14' day;"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "select\n    time,\n    consumed_energy / 3600000 as \"Consumed\"\nfrom\n\t  daily_energy\nwhere time > now() - interval '14' day;"
    }
   ]
  }
 ]
}